apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-manager-controller-role
  namespace: open-cluster-management-hub
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
