{{- if .Values.agent.redis.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.redis.secretName }}
  namespace: argocd
type: Opaque
data:
  {{- if .Values.agent.redis.username }}
  username: {{ .Values.agent.redis.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.agent.redis.password }}
  password: {{ .Values.agent.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}
