kind: Deployment
apiVersion: apps/v1
metadata:
  name: hellospoke-addon-manager
  namespace: open-cluster-management
  labels:
    app: hellospoke-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellospoke-addon-manager
  template:
    metadata:
      labels:
        app: hellospoke-addon-manager
    spec:
      serviceAccountName: hellospoke-addon-sa
      containers:
      - name: hellospoke-addon-manager
        image: quay.io/open-cluster-management/addon-contrib/hellospoke-addon:latest
        imagePullPolicy: IfNotPresent
        args:
          - "manager"
